version: '2'
services:
    routerpractice-app:
        image: routerpractice
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://routerpractice-mysql:3306/routerpractice?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    routerpractice-mysql:
        extends:
            file: mysql.yml
            service: routerpractice-mysql
